[package]
name = "rookie-codes/windlines"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
description = "Creates animated wind line visual effects in the 3D world using Attachments and Trails. Designed for use in open environments to simulate wind gusts, breezes, or magical effects."
realm = "shared"

[dependencies]
